{% set name = "pepredicates" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 80a8476fbdca517e1736dc82590793402849eb87522b481dd027c8744fc39d87

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - astropy >=4.0
    - matplotlib-base
    - numpy
    - python >=3.6
    - seaborn

test:
  imports:
    - pepredicates

about:
  home: https://charlie.hoy.docs.ligo.org/pepredicates/index.html
  doc_url: https://charlie.hoy.docs.ligo.org/pepredicates/index.html
  license: AGPL-3.0
  license_family: AGPL
  license_file: LICENSE
  summary: Code for computing various P_BLAH quantities in a general way from PE samples.
  description: |
    Code for computing various P_BLAH quantities in a general way from PE
    samples.
extra:
  recipe-maintainers:
    - hoyc1
