{% set name = "pepredicates" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3bc4700bf32f6eb6562446e01aadec3403ba57f1de04bb5b26332dad4cdad1f5

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - astropy>=4.0
    - matplotlib-base
    - numpy
    - python >=3.6
    - seaborn

test:
  imports:
    - pepredicates

about:
  home: https://charlie.hoy.docs.ligo.org/pepredicates/index.html
  doc_url: https://charlie.hoy.docs.ligo.org/pepredicates/index.html
  license: AGPL-3.0
  license_family: AGPL
  license_file: LICENSE
  summary: Code for computing various P_BLAH quantities in a general way from PE samples.
  description: |
    Code for computing various P_BLAH quantities in a general way from PE
    samples.
extra:
  recipe-maintainers:
    - hoyc1
